### ISSUE TITLE
Need source for DMRGateway to build for different env

### ISSUE THREAD

**Issue by ryanturner** [N4IRS/Analog_Bridge#1]
Hi,

I'd love to make use of this, but not using a raspberry pi. Since there's just a bin here instead of sources, there's no way for us to. Please add sources so others can build and use this on an x86 platform!

**Comment by mzingman** [comment]
Hello Ryan,

That is the plan.  The code is not ready yet for publication, but it should be very soon.

**Comment by millma** [comment]
Hi,
Any progress on preparing the source code? I'd love to learn more about this project and help where I can.
