### ISSUE TITLE
Add support for software transcoding

### ISSUE THREAD

**Issue by brovary3154** [N4IRS/Analog_Bridge#8]
I'd be more apt to play with this bridge if it didn't require the use of a hardware transcoder.  And it would be viable for remote datacenter locations.  There is some good work in the op25 project for software AMBE support.  https://github.com/boatbod/op25/tree/master/op25/gr-op25_repeater/lib

Thanks

**Comment by N4IRS** [comment]
You are correct. We have been working with the OP25 code for quite a while. Also with other software methods. Stay tuned.

**Comment by brovary3154** [comment]
Awesome.  Thanks
--------------------------------------------
On Sun, 4/8/18, Steve Zingman <notifications@github.com> wrote:

 Subject: Re: [N4IRS/Analog_Bridge] Add support for software transcoding (#8)
 To: "N4IRS/Analog_Bridge" <Analog_Bridge@noreply.github.com>
 Cc: "brovary3154" <brovary3154@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, April 8, 2018, 5:53 PM
 
 You are correct. We have been
 working with the OP25 code for quite a while. Also with
 other software methods. Stay tuned.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.
